<a href="https://colab.research.google.com/github/Amulyar04/python_amulya/blob/main/lab6_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Code Implementation of scalar, vector and matrix using Numpy

import numpy as np

# Defining a Scalar (O_D array)
scalar = np.array(6)
print("Scalar:",scalar)
print("Scalar shape:", scalar.shape)
# Performing basic operations
scalar_addition = scalar + 2
print("Scalar after addition:", scalar_addition)

Scalar: 6
Scalar shape: ()
Scalar after addition: 8


In [ ]:
# Defining a Vector (1-D array)
vector = np . array ([4,5,6])
print("\nvector:", vector)
print("vector shape:", vector . shape)

# Performing basic operations
vector_addition = vector + 3
print("vector after addition:", vector_addition)


vector: [4 5 6]
vector shape: (3,)
vector after addition: [7 8 9]


In [ ]:
# Defininig a Matrix (2-D array)
matrix = np.array([[2,3,4], [4,5,6]])
print("\nMatrix:\n", matrix)
print("Matrix shape:", matrix .shape)
# performing basic operations
matrix_multiplication = matrix * 3
print("Matrix after multiplication:\n", matrix_multiplication)


Matrix:
 [[2 3 4]
 [4 5 6]]
Matrix shape: (2, 3)
Matrix after multiplication:
 [[ 6  9 12]
 [12 15 18]]
