<a href="https://colab.research.google.com/github/Amulyar04/python_amulya/blob/main/lab_6_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
# Import necessary library
import numpy as np
# Create matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
# Addition of Two Matrix
addition_result = A + B
print("Matrix Addition:\n", addition_result)
# Subtraction of Two Matrix
subtraction_result = A - B
print("Matrix Subtraction:\n", subtraction_result)
# Element-wise Multiplication
elementwise_multiplication = A * B
print("Element-wise Multiplication:\n", elementwise_multiplication)
# Normal Matrix Multiplication (Dot Product)
matrix_multiplication = np.dot(A, B)
print("Matrix Multiplication (Dot Product):\n", matrix_multiplication)
# Transpose of a Matrix
transpose_A = A.T
print("Transpose of Matrix A:\n", transpose_A)


Matrix Addition:
 [[ 6  8]
 [10 12]]
Matrix Subtraction:
 [[-4 -4]
 [-4 -4]]
Element-wise Multiplication:
 [[ 5 12]
 [21 32]]
Matrix Multiplication (Dot Product):
 [[19 22]
 [43 50]]
Transpose of Matrix A:
 [[1 3]
 [2 4]]
